### ISSUE TITLE
Graph arrow key does not show becuase of this plugin

### ISSUE THREAD

**Issue by jayu9493** [Seraphli/obsidian-link-embed#11]
As the title says In new update of obsidian 1.1.8 when this plugin is running arrow in canvas do not show and after turning off this plugin arrows are visible.

https://user-images.githubusercontent.com/87773845/208963866-2e5a58a5-ccd5-4e2b-9833-cebf43982049.mp4

**Comment by Seraphli** [comment]
Fixed in https://github.com/Seraphli/obsidian-link-embed/commit/c92473a62928bc5ce2cea3e528648a03d0d3353a
