### ISSUE TITLE
Question: is it possible to embed links which require authentication?

### ISSUE THREAD

**Issue by klauern** [Seraphli/obsidian-link-embed#12]
Hello!  I have been using this plugin and was curious if there was a way to authenticate embedded links so you can get at the content?  I see that there are several embed options, but I am not sure if they provide ways to link into something like your Jira account or a Google Drive or something.

Along those lines, is there a way to embed locally such that it opens a browser to retrieve page details?  I was thinking something like Playwright/Puppeteer or something, but that might be wildly afar from what your plugin is doing, though.

**Comment by Seraphli** [comment]
Technically, yes. I only extract the meta information of the URL from a website and parse the data. If you can have a website that provides those meta infos of URLs, I think I can come up with some settings that offer the ability to customize fetching URL and template.
So the question is, do you have such a website or server?

**Comment by Seraphli** [comment]
I will close this issue for now. Feel free to comment.
