### ISSUE TITLE
Internal Links issue

### ISSUE THREAD

**Issue by vikkr** [Seraphli/obsidian-link-embed#13]
After installing the plugin, the Internal Links lose their blue color. No issues with external links, only Internal links.

**Comment by Seraphli** [comment]
Please let me know how to reproduce this issue with screenshots. I tried to disable the plugin but the internal links are always black.
<img width="517" alt="image" src="https://user-images.githubusercontent.com/1586755/211181528-aa1cf66a-1861-4e0d-bfad-76c9b4bb3146.png">

**Comment by vikkr** [comment]
<img width="292" alt="Screen Shot 2023-01-08 at 4 51 46 pm" src="https://user-images.githubusercontent.com/10242217/211184273-36c3eade-f6ed-492c-b36d-cc2394848382.png">

<img width="267" alt="Screen Shot 2023-01-08 at 4 52 56 pm" src="https://user-images.githubusercontent.com/10242217/211184283-4ec9448d-c0c7-4567-8bc7-a6f0b2a8f570.png">

I have minimal theme installed. The backlinks are displayed as blue font. After installing the plugin, the blue font is gone, it displays as black font. Once I disable the plugin then internal links are again displayed as blue font. It affects only internal links, external links are fine.

**Comment by vikkr** [comment]
These are normal backlinks.

<img width="494" alt="Screen Shot 2023-01-08 at 4 59 37 pm" src="https://user-images.githubusercontent.com/10242217/211184411-65427fae-e4f0-4890-8ba0-353a854d4caf.png">

**Comment by Seraphli** [comment]
I can not reproduce this issue.

Live Preview
<img width="519" alt="image" src="https://user-images.githubusercontent.com/1586755/211185219-c1174bf4-fa5f-4569-9202-44a2f11ae19f.png">
Source Mode
<img width="322" alt="image" src="https://user-images.githubusercontent.com/1586755/211185228-301e4c0a-cb3e-49be-b158-1a437482048b.png">
Theme
<img width="770" alt="image" src="https://user-images.githubusercontent.com/1586755/211185239-0ad41e8f-1b49-4cd2-8b52-4b022a03f689.png">
Plugin
<img width="779" alt="image" src="https://user-images.githubusercontent.com/1586755/211185245-957d6f65-1b46-4bfd-a708-58b2ac128ff5.png">

**Comment by Seraphli** [comment]
I will close this issue for now. Feel free to comment.
