### ISSUE TITLE
[Feature request] 16:9 image size, the 1:1 now is too narrow, the text part is too wide.

### ISSUE THREAD

**Issue by wenbopeng** [Seraphli/obsidian-link-embed#14]
Thanks for your great idea!

16:9 image size, the 1:1 now is too narrow, the text part is too wide. Reduce the width of the text and increase the width of the image.

![image](https://user-images.githubusercontent.com/74350447/214518803-16b86e8b-6f3c-41b1-a620-9b00fb8eb6b0.png)

**Comment by Seraphli** [comment]
Thanks for your support. Unfortunately, I'm not good at CSS, and the original style references other websites. I use this plugin mainly to extract text information from URLs. After all, you can not search the text on images in Obsidian.
And considering the varying size of the image, the feature might have to provide different styles for different images, or auto switch between styles based on the image size. As I said, I'm not good at CSS, so I honestly don't know how to implement such a feature.
If you like to modify the width of the image, you can fork this repo and create a revised version. This plugin is relatively stable for now, so a fork is recommended.

**Comment by wenbopeng** [comment]
I have solved this issue, this is the css code

```css
._lc._sm:not(.xd) .wc {
    min-width: 300px;
    min-height: 169px;
}

a.c{
  min-width: 300px;
  min-height: 169px;
}

.e {
  padding-bottom: 0% !important;
}
```
![image](https://user-images.githubusercontent.com/74350447/214529407-7a98690e-ce79-48d4-91c5-5ba32fc48fae.png)


![image](https://user-images.githubusercontent.com/74350447/214528591-605f9192-010d-4878-b8a3-9ab41955efb9.png)

![image](https://user-images.githubusercontent.com/74350447/214528649-0c9c2506-e297-4140-87b6-c4798579ee8c.png)


perfect~!

**Comment by Seraphli** [comment]
That's Great! The CSS snippet may be useful for others. Thank you for sharing!
