### ISSUE TITLE
Embeded block is super long with images pasted under it.

### ISSUE THREAD

**Issue by DudeThatsErin** [Seraphli/obsidian-link-embed#16]
I created an embed automatically and then pasted images after it and it was making the embed super long for no reason.
In the screenshots I provide below, you can see that it spans longer than 2 pages. I thought adding the random letters before the images would help but they do not. I have tried re-creating the images as well as enabling debug mode to see any errors. No errors it is just super long for no reason.

The last screenshot I am adding (3rd) it is simply there so you can see how far down the page I had to scroll before I got to my screenshots/text.
![image](https://user-images.githubusercontent.com/2681022/219109077-392de9e0-7ef7-4dac-834e-7d9ee9b13a39.png)
![image](https://user-images.githubusercontent.com/2681022/219109347-10851708-d6d4-4d3a-9789-a69d4ecab0ab.png)
![image](https://user-images.githubusercontent.com/2681022/219109392-0ebdc66a-cee1-490c-aba4-dd8652b60036.png)

Here is a gif video showing this as well: [https://i.imgur.com/x2cprk8.gif](https://i.imgur.com/x2cprk8.gif)

I don't understand why this is happening.

**Comment by Seraphli** [comment]
I can not reproduce it. Maybe there is a conflict between plugins. Can you disable other plugins and see if this issue still exists?
![image](https://user-images.githubusercontent.com/1586755/219244059-3576fbf2-81e4-4955-a080-e14f3e69ade7.png)

**Comment by Seraphli** [comment]
Closed due to inactivation.
