### ISSUE TITLE
Description or titles with special characters in them need to be cleaned prior to being embedded

### ISSUE THREAD

**Issue by TheMerricat** [Seraphli/obsidian-link-embed#17]
Example - https://www.nexusmods.com/skyrimspecialedition/mods/59818

If I attempt to embed this link it will always fail because in the description that gets pulled is:

> Generates crash logs when the game Just Works™. This is a SSE/AE/VR port using fudgyduff's MIT source. This can read PDB files that mod authors may distribute. 

And the apostrophe in _fudgyduff's_ causes the string to be terminated early. As far as I can tell there is no 'safe' way to escape this mark in the string, it simply needs to be stripped out.

**Comment by Seraphli** [comment]
![image](https://user-images.githubusercontent.com/1586755/221376168-df3856cd-d08e-42bf-a7c5-a6c44aa06478.png)
I tried but there was no error. I didn't get what you mean by failure. Perhaps you can describe the expected behavior for me.

**Comment by TheMerricat** [comment]
So this is embarrassing, I spent a good three hours trying to track down the problem and can't reproduce it today.... Everything is working fine. I'm not sure what changed between then and now. I pretty much closed that note and waited for a response before moving forward. Either way, sorry for wasting your time.

**Comment by Seraphli** [comment]
Because this meta info is pulled from other websites, there might be an issue with their API yesterday.
