### ISSUE TITLE
Not works with youtube link.

### ISSUE THREAD

**Issue by sevelee** [Seraphli/obsidian-link-embed#18]
For example, I have a link https://www.youtube.com/watch?v=k__gEeVPiLg&ab_channel=SweetGirl.

The parse result is:
![image](https://user-images.githubusercontent.com/8036235/229403782-8a71d515-4aa6-4107-a1fd-6fe602dc729d.png)
![image](https://user-images.githubusercontent.com/8036235/229403790-a37d6ca7-f147-4ef6-a98b-db0f5464bc5e.png)

Which I thought it should be like this:
![image](https://user-images.githubusercontent.com/8036235/229403980-60fc9aed-830b-43df-b023-aae7986c2524.png)
![image](https://user-images.githubusercontent.com/8036235/229403996-acf10222-e4b9-4d21-8adc-74b5da27714b.png)

**Comment by sevelee** [comment]
Update.

I changed primary parser from MicroLink to JSONLink, it works.
So seems there's some bugs with MicroLink?

**Comment by sevelee** [comment]
Update.
JSONLink not works well with "https://www.shadertoy.com". Couldn't fetch any information.
![image](https://user-images.githubusercontent.com/8036235/229420612-d63ac93a-c13b-414a-8943-831c0a69e853.png)


Maybe could have mode that fetch three methods together then use the longest infomation one?

**Comment by Seraphli** [comment]
For Youtube, you can use the share link provided by Youtube. That link will work fine.
For your example, `https://youtu.be/k__gEeVPiLg` is the link.
![image](https://user-images.githubusercontent.com/1586755/229421338-62150bbb-3155-4b4b-9651-039ffd9bc528.png)

**Comment by Seraphli** [comment]
`https://www.shadertoy.com/` seems working fine.
![image](https://user-images.githubusercontent.com/1586755/229421617-0cdea308-850d-4cf8-8df1-7d27cce03732.png)

BTW, I'm using MicroLink. JSONLink might have some problems sometimes. That's why I set the primary parser to Microlink.

**Comment by sevelee** [comment]
> For Youtube, you can use the share link provided by Youtube. That link will work fine. For your example, `https://youtu.be/k__gEeVPiLg` is the link. ![image](https://user-images.githubusercontent.com/1586755/229421338-62150bbb-3155-4b4b-9651-039ffd9bc528.png)

yes, share link provided by Youtube works.

Maybe could have a mode that fetch three methods at same time, then use the longest infomation one as result? Which will have a highly possibility is the right one

**Comment by Seraphli** [comment]
Sometimes the longest information is not the correct information. It depends more on the parser site, rather than the length of the results. Another question is whether should I mix all parser's result to get the longest information. For example, taking the title from one parser and the description from another. It's difficult to find a perfect way, as long as you can not modify the returns from the parser site. The best way I think is to find a better parser.
