### ISSUE TITLE
Why your plugin does conflict with RTL support for Obsidian?

### ISSUE THREAD

**Issue by 7Codez** [Seraphli/obsidian-link-embed#20]
Can you solve it so that why your plugin does conflict with RTL support for Obsidian?
Because it works perfectly with all add-ons except yours?
What is happening?????

**Comment by Seraphli** [comment]
Could you provide more information for reproducing the issue?

**Comment by 7Codez** [comment]
Install
https://github.com/esm7/obsidian-rtl
And
https://github.com/Seraphli/obsidian-link-embed
obsidian-rtl will crash if you enable obsidian-link-embed

**Comment by 7Codez** [comment]
Why does your own plugin only cause problems with obsidian-rtl plugin?
What is happening?????

**Comment by Seraphli** [comment]
<img width="772" alt="image" src="https://github.com/Seraphli/obsidian-link-embed/assets/1586755/c591fbb9-d254-4d6f-9049-ac5213ff745c">
<img width="868" alt="image" src="https://github.com/Seraphli/obsidian-link-embed/assets/1586755/3190ce89-0105-45ab-b207-9ec69c3bdd8a">
No crash here.

**Comment by 7Codez** [comment]
This is an English text that is LTR, and it must start writing from left to right, that is, it should be aligned with the left direction.
"
Hello
how are you my friend?
"

This is an Arabic text that is RTL, and it must start writing from right to left, that is, it should be aligned with a right direction.
"
السلام عليكم؜؜
كيف حالك صديقي؟؜؜
"

problem like this:

السلام عليكم؜؜
كيف حالك صديقي؟؜؜

**Comment by 7Codez** [comment]
This is an English text that is LTR, and it must start writing from left to right, that is, it should be aligned with the left direction.
"
Hello
how are you my friend?
"

This is an Arabic text that is RTL, and it must start writing from right to left, that is, it should be aligned with a right direction.

السلام عليكم؜؜
كيف حالك صديقي؟؜؜


problem like this:
السلام عليكم؜؜
كيف حالك صديقي؟؜؜

**Comment by Seraphli** [comment]
Fixed in 2.0.4. Check the new version.
