### ISSUE TITLE
Wrong version in manifest.json?

### ISSUE THREAD

**Issue by hsiktas** [Seraphli/obsidian-link-embed#21]
Obsidian always offers me to update to version 2.0.4, but that version seems to have the previous version number in its manifest.json: https://github.com/Seraphli/obsidian-link-embed/releases/tag/2.0.4

The result is that the installed version is always assumed to be 2.0.3, and it will always offer me to update it.

**Comment by Seraphli** [comment]
Thanks for pointing out. Fixed. Sorry for that trouble.
