### ISSUE TITLE
Links are stuck Fetching

### ISSUE THREAD

**Issue by fischgeek** [Seraphli/obsidian-link-embed#23]
Most of the time, when I paste a link it just sits there and spins on the default Fetching. Other links are slow to render as well. How can I speed this up and avoid long waits or spinning Fetches?

**Comment by Seraphli** [comment]
You might need to test connections between three parser websites. Then choose the right one. The parser links can be found in https://github.com/Seraphli/obsidian-link-embed/blob/main/parser.ts

**Comment by fischgeek** [comment]
Wow. Yeah, JSONLink is way faster. Thanks!
