### ISSUE TITLE
In the live preview the link occupies the entire width of the screen.

### ISSUE THREAD

**Issue by martin-arg** [Seraphli/obsidian-link-embed#24]
I just install this plugin, and thanks, it's very usefull. But it looks ugly as seen in the live preview. In reading view the width is fine. Can it be modified?

Live preview
![imagen](https://github.com/Seraphli/obsidian-link-embed/assets/7675317/f3d98e7b-2d79-48d2-a2ee-6b923f2ba598)

Reading view

![imagen](https://github.com/Seraphli/obsidian-link-embed/assets/7675317/0447d1ae-afa9-4a4b-b215-4a7cea7c8cd4)

**Comment by Seraphli** [comment]
I don't have this issue. Please try to disable other plugins and see if the problem still exists.
![image](https://github.com/Seraphli/obsidian-link-embed/assets/1586755/a24d9eab-2eca-4ee1-be84-62a7928280f3)
There might be some CSS conflictions.

**Comment by martin-arg** [comment]
Sorry I didn't respond before, but you are right. There is a problem with the theme "minimal". Once I disable it the boxes show perfect. thanks
