### ISSUE TITLE
Clash with Auto Link Title plugin

### ISSUE THREAD

**Issue by robertandrews** [Seraphli/obsidian-link-embed#29]
I'm not sure if there's anything that can be done about this, but...

https://github.com/zolrath/obsidian-auto-link-title

Auto Link Title fetches the title of a remote URL and uses that as the link title. When this is enabled, it limits obsidian-link-embed from working. while the Create Embed option briefly appears before the title is added, it does not appear to work correctly.

**Comment by Seraphli** [comment]
I believe these two plugins have conflicting functions. You might only be able to choose one, or turn off the automatic title-adding feature of the other plugin.
