### ISSUE TITLE
[Feature] Detect the URL at the cursor without having to select it

### ISSUE THREAD

**Issue by huyz** [Seraphli/obsidian-link-embed#3]
It would be nice if the function "From Selection" would not require the user to select the whole URL: just having the cursor anywhere inside the URL should be sufficient.

An example of a plugin that does it this way: https://github.com/zolrath/obsidian-auto-link-title

**Comment by Seraphli** [comment]
Done e13d4699fe0fce91b4ac1ec48543c800556c3e0d
