### ISSUE TITLE
unable to generate thumbnails - some sites

### ISSUE THREAD

**Issue by Jopp-gh** [Seraphli/obsidian-link-embed#32]
**Link embed** works nicely except for some e-com sites:
```
https://www.buymeacoffee.com
https://flattr.com
https://www.gofundme.com/
https://liberapay.com
https://www.2checkout.com
```

**Comment by Seraphli** [comment]
There might be some problems with Local Parser. You can try with MicroLink.
<img width="783" alt="image" src="https://github.com/Seraphli/obsidian-link-embed/assets/1586755/3f0f5493-11de-4d81-b614-9470e291f4c1">

**Comment by Seraphli** [comment]
I tried with the latest version. It seems to be working fine.

**Comment by Jopp-gh** [comment]
I did use both MicroLink (alternative JsonLink) and your latest version last time, but was nevertheless unable to generate thumbs

Now I tried again and got it working, so it must have been bad network on my side
Thanks for your great plugin!
