### ISSUE TITLE
Link embed displays correctly on obsidian but won't appear on the exported pdf

### ISSUE THREAD

**Issue by Manrochri** [Seraphli/obsidian-link-embed#33]
I tested this plugin and it works correctly inside obsidian. However, when I export my markdown file to pdf, those embed links won't appear. I'm using a windows 10 computer with the obsidiant deskptop app and I'm exporting the pdf while I'm in the reading mode. I hope's there's a solution for this, because I believe the embeds look really good.

**Comment by Seraphli** [comment]
It's an issue with Obsidian I think. Currently, this plugin uses `registerMarkdownCodeBlockProcessor` to render the block. I didn't find any solution after doing a few searches. You can ask about this problem on the forum, or maybe find another plugin that can render when exporting. I will implement that if there is a solution.
