### ISSUE TITLE
Embeds taking up entire card height

### ISSUE THREAD

**Issue by jonyTF** [Seraphli/obsidian-link-embed#36]
When a note is selected in Obsidian canvas, the embeds take up the entire height of the card, but when unselected, the embeds look fine

https://github.com/Seraphli/obsidian-link-embed/assets/16812809/cd31591b-731e-49d3-82fc-5727a7a3923a

**Comment by Seraphli** [comment]
Can you provide a markdown file to reproduce this?

**Comment by jonyTF** [comment]
It's technically a .canvas file, here it is:
https://drive.google.com/file/d/1ioy_-Al-otloW08Fj3mgF3KCOtXMzD7l/view?usp=sharing
