### ISSUE TITLE
Need to flush cache

### ISSUE THREAD

**Issue by hillysong** [Seraphli/obsidian-link-embed#39]
When creating "embed", there might be an error or problem. In that case, error image is shown in the embed, which, however, has 
a correct url inside. If I remove and re-paste the url link again, the same error image is shown despite of no problem. I think there is a internal cache. If so, it should be cleared when the user wants.

**Comment by Seraphli** [comment]
This plugin didn't cache anything. You need to reload Obsidian in order to refresh the cache. The plugin has no control about cache. It just call fetching API.

**Comment by Endermanbugzjfc** [comment]
Thought I had the same problem before realising the URL was incorrect. I would say this issue should be pinned.
