### ISSUE TITLE
[Feature] Combine "From clipboard" and "Use selection" into one shortcut

### ISSUE THREAD

**Issue by huyz** [Seraphli/obsidian-link-embed#4]
I wish the two functions "From clipboard" and "Use selection" were combined into one:

- If text is highlighted and corresponds to a URL (or cursor is inside a URL if https://github.com/Seraphli/obsidian-link-embed/issues/3 is implemented), then use that.
- Otherwise, look in the clipboard and see if there's a URL there, then use that.

**Comment by Seraphli** [comment]
Good idea. I checked the repo you referred to. It certainly saves my time. I'm currently working on another project. I will update the plugin when I get some time.

**Comment by Seraphli** [comment]
Done e13d4699fe0fce91b4ac1ec48543c800556c3e0d
