### ISSUE TITLE
Internal link

### ISSUE THREAD

**Issue by Aetherinox** [Seraphli/obsidian-link-embed#41]
Hey, is their a way to integrate internal links? I tried with copying the Obsidian url, but the issue with that is that links open in a brand new Obsidian instance, instead of just opening the note.

```
obsidian://open?vault=Name&file=whatever
```

**Comment by Seraphli** [comment]
I tried on my Obsidian 1.6.7. The link just open the note in the current page. I don't have this issue.

**Comment by Aetherinox** [comment]
Hrm... wonder if there's a setting somewhere in Obsidian that needs changed. Every link I click opens a brand new instance of my vault.

**Comment by Seraphli** [comment]
Try to disable other plugins and test again.
