### ISSUE TITLE
Bug: if the URL is a Markdown link, the embed should be outside of link

### ISSUE THREAD

**Issue by huyz** [Seraphli/obsidian-link-embed#5]
If I select the URL inside of a Markdown link, then the embed appears inside of the Markdown link, thus breaking it.
In other words, the closing parenthesis `)` ends up after the embed.

**Comment by Seraphli** [comment]
Yes, currently this plugin only replaces the selection, not making a new line at the end of the previous line. I can change the default behavior in the next update.

**Comment by Seraphli** [comment]
Fixed in e13d4699fe0fce91b4ac1ec48543c800556c3e0d
