### ISSUE TITLE
Preview unfolding

### ISSUE THREAD

**Issue by stdusr** [Seraphli/obsidian-link-embed#7]
When I click on the link preview in editing mode, it opens the link but also unfolds and shows it's HTML. In reading mode it's OK. Is there something I can do to prevent unfolding in editing mode?

**Comment by Seraphli** [comment]
I don't have this issue under Live Preview mode. I click on the title and it doesn't unfold the block. It only unfolds when the cursor move in to the block.

**Comment by j3sch** [comment]
I noticed it too. The extension Rich Links has the same problem.

**Comment by Seraphli** [comment]
It might be caused by Obsidian, because the default behavior to handle the click is defined by Obsidian. Plugins can not change this.

**Comment by j3sch** [comment]
> It might be caused by Obsidian, because the default behavior to handle the click is defined by Obsidian. Plugins can not change this.

Yes, I also think it is caused by obsidian. I tried to fix it, but wasn't possible for me.

**Comment by Seraphli** [comment]
Some plugins like dataview only show embed in the editor, not in the source file. So I guess they don't have this issue. But I want to embed the preview in order to search for them. So I will not use this way.

**Comment by Seraphli** [comment]
@j3sch @stdusr Check out the new version 2.0.0, which should fix this issue. You can convert your old embeds to new code blocks with the `Convert` button in the setting. I tested it, but I'm not sure there is a bug. Remember to leave a comment for feedback.

**Comment by stdusr** [comment]
Works fine, many thanks!

**Comment by Seraphli** [comment]
Solved in verion 2.0.0

**Comment by j3sch** [comment]
Thank you very much, it works perfectly.

**Comment by Seraphli** [comment]
I notice there is a bug in the `Convert` function. I fixed it in the new version. You might have to revert some changes and use the new `Convert` button.
