### ISSUE TITLE
Spelling mistake in link embed settings

### ISSUE THREAD

**Issue by Tanzeel159** [Seraphli/obsidian-link-embed#9]
There is small spelling mistake in link embed settings
Remvoe dismiss instead of remove dismiss
![Screenshot from 2022-10-03 13-46-05](https://user-images.githubusercontent.com/20295349/193531214-5ef94de5-f3dc-43dd-8b36-62357ebf4323.png)

**Comment by Seraphli** [comment]
Thanks! Fixed. https://github.com/Seraphli/obsidian-link-embed/commit/aea433372ba73c18a6849a14b80bf960444d3132
